# Generated by Django 5.1.6 on 2025-03-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maria', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
